import os  # Provides access to operating-system environment variables.
import sqlite3  # Provides SQLite database access for the original local database.
import psycopg  # Provides PostgreSQL database access.
from psycopg import sql  # Provides safe SQL construction for table and column identifiers.

SQLITE_DB = "hardware_inventory.db"  # Stores the filename of the original SQLite database.
DATABASE_URL = os.getenv("DATABASE_URL")  # Reads the PostgreSQL connection string from the environment.

if not DATABASE_URL:  # Checks whether the PostgreSQL connection string was provided.
    raise RuntimeError("DATABASE_URL is not set.")  # Stops the migration if the connection string is missing.

sqlite_conn = sqlite3.connect(SQLITE_DB)  # Opens the original SQLite database.
sqlite_conn.row_factory = sqlite3.Row  # Allows SQLite rows to be accessed by column name.
pg_conn = psycopg.connect(DATABASE_URL)  # Opens a connection to the Supabase PostgreSQL database.
pg_conn.autocommit = False  # Uses a transaction so changes can be rolled back if an error occurs.

try:  # Starts the protected migration section.
    pg_cur = pg_conn.cursor()  # Creates a PostgreSQL cursor for SQL commands.
    sqlite_cur = sqlite_conn.cursor()  # Creates a SQLite cursor for reading source data.

    table_definitions = {  # Defines the PostgreSQL tables required by the application.
        "users": [  # Matches the SQLite users table.
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "email TEXT UNIQUE NOT NULL",
            "password_hash TEXT NOT NULL",
            "locked INTEGER NOT NULL DEFAULT 0",
            "role TEXT NOT NULL DEFAULT 'user'",
        ],

        "password_reset_requests": [  # Matches the SQLite password_reset_requests table.
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "user_id BIGINT NOT NULL",
            "new_password_hash TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'pending'",
            "created_at BIGINT NOT NULL",
                "FOREIGN KEY (user_id) REFERENCES users(id)",
        ],

        "hardware": [  # Matches the SQLite hardware table.
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT NOT NULL",
            "category TEXT NOT NULL",
            "quantity INTEGER NOT NULL",
            "unit_price DOUBLE PRECISION NOT NULL",
            "status TEXT NOT NULL",
        ],

        "borrow_records": [  # Matches the SQLite borrow_records table.
            "borrow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "student_name TEXT NOT NULL",
            "student_id TEXT NOT NULL",
            "borrow_date TEXT NOT NULL",
            "class_name TEXT NOT NULL",
            "schedule TEXT NOT NULL",
            "room TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'Borrowed'",
            "requested_by TEXT NOT NULL DEFAULT ''",
            "returned_at TEXT",
        ],

        "borrow_items": [
            "borrow_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "borrow_id BIGINT NOT NULL",
            "item_id BIGINT NOT NULL",
            "quantity INTEGER NOT NULL",
            "FOREIGN KEY (borrow_id) REFERENCES borrow_records(borrow_id)",
            "FOREIGN KEY (item_id) REFERENCES hardware(item_id)",
        ],
    }

    for table_name, columns in table_definitions.items():
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(sql.Identifier(table_name), column_sql)
        pg_cur.execute(create_sql)

    counts = {}
    sqlite_table_map = {
        "users": "users",
        "password_reset_requests": "password_reset_requests",
        "hardware": "hardware",
        "borrow_records": "borrow_records",
        "borrow_items": "borrow_items",
    }

    for table_name in table_definitions:
        source_table = sqlite_table_map[table_name]
        pg_cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name)))
        destination_count = pg_cur.fetchone()[0]

        if destination_count > 0:
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")

        sqlite_cur.execute(f"SELECT * FROM {source_table}")
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)

        if not rows:
            continue

        source_columns = [description[0] for description in sqlite_cur.description]
        insert_columns = source_columns[:]

        if table_name == "borrow_records" and "requested_by" not in insert_columns:
            insert_columns.append("requested_by")

        for row in rows:
            values = [row[column] for column in source_columns]
            if table_name == "borrow_records" and "requested_by" not in [c.lower() for c in source_columns]:
                values.append("")

            pg_insert_columns = ", ".join(sql.Identifier(column).as_string(pg_conn) for column in insert_columns)
            placeholders = ", ".join(["%s"] * len(insert_columns))
            insert_sql = f"INSERT INTO {table_name} ({pg_insert_columns}) VALUES ({placeholders})"
            pg_cur.execute(insert_sql, values)

    sequence_columns = {
        "users": "id",
        "password_reset_requests": "id",
        "hardware": "item_id",
        "borrow_records": "borrow_id",
        "borrow_items": "borrow_item_id",
    }

    for table_name, id_column in sequence_columns.items():
        sequence_sql = sql.SQL(
            "SELECT setval(pg_get_serial_sequence({}, {}), COALESCE(MAX({}), 0), MAX({}) IS NOT NULL) FROM {}"
        ).format(
            sql.Literal(table_name),
            sql.Literal(id_column),
            sql.Identifier(id_column),
            sql.Identifier(id_column),
            sql.Identifier(table_name),
        )
        pg_cur.execute(sequence_sql)

    pg_conn.commit()
    print("Migration completed successfully.")
    print(f"  users:            {counts['users']}")
    print(f"  password_reset_requests:  {counts['password_reset_requests']}")
    print(f"  hardware:         {counts['hardware']}")
    print(f"  borrow_records:   {counts['borrow_records']}")
    print(f"  borrow_items:     {counts['borrow_items']}")

except Exception:
    pg_conn.rollback()
    raise

finally:
    sqlite_conn.close()
    pg_conn.close()
