import csv
import sqlite3
import psycopg
import io
from datetime import date
from logger import logger
from models.database import column_exists, get_db_connection, is_postgres_enabled, now_sql
from models.schemas import InventoryItemSchema
from pydantic import ValidationError

class TrackerController:
    def __init__(self, db_name="hardware_inventory.db"):
        self.db_name = db_name

    def _connect(self):
        return get_db_connection(self.db_name)

    def get_all_items(self, search_text="", category="ALL"):
        return self.search_items(search_text, category)

    def delete_bulk_items(self, item_ids):
        if not item_ids:
            return False, "Select at least one inventory item."
        results = [self.delete_item(item_id) for item_id in item_ids]
        failures = [message for ok, message in results if not ok]
        return (False, failures[0]) if failures else (True, "Selected items deleted successfully.")

    def _ensure_table(self):
        with self._connect() as conn:
            cursor = conn.cursor()
            if is_postgres_enabled():
                cursor.execute(
                    "CREATE TABLE IF NOT EXISTS hardware ("
                    "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "item_name TEXT UNIQUE NOT NULL, "
                    "category TEXT NOT NULL, "
                    "quantity INTEGER NOT NULL, "
                    "unit_price DOUBLE PRECISION NOT NULL, "
                    "status TEXT NOT NULL)"
                )
                cursor.execute(
                    "CREATE TABLE IF NOT EXISTS borrow_records ("
                    "borrow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "student_name TEXT NOT NULL, student_id TEXT NOT NULL, "
                    "borrow_date TEXT NOT NULL, class_name TEXT NOT NULL, "
                    "schedule TEXT NOT NULL, room TEXT NOT NULL, "
                    "status TEXT NOT NULL DEFAULT 'Borrowed', returned_at TEXT)"
                )
                if not column_exists(conn, "borrow_records", "requested_by"):
                    cursor.execute("ALTER TABLE borrow_records ADD COLUMN requested_by TEXT NOT NULL DEFAULT ''")
                cursor.execute(
                    "CREATE TABLE IF NOT EXISTS borrow_items ("
                    "borrow_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "borrow_id BIGINT NOT NULL, item_id BIGINT NOT NULL, "
                    "quantity INTEGER NOT NULL)"
                )
                return

            cursor.execute(
                "CREATE TABLE IF NOT EXISTS hardware ("
                "item_id INTEGER PRIMARY KEY AUTOINCREMENT, "
                "item_name TEXT UNIQUE NOT NULL, "
                "category TEXT NOT NULL, "
                "quantity INTEGER NOT NULL, "
                "unit_price REAL NOT NULL, "
                "status TEXT NOT NULL)"
            )
            cursor.execute(
                "CREATE TABLE IF NOT EXISTS borrow_records ("
                "borrow_id INTEGER PRIMARY KEY AUTOINCREMENT, "
                "student_name TEXT NOT NULL, student_id TEXT NOT NULL, "
                "borrow_date TEXT NOT NULL, class_name TEXT NOT NULL, "
                "schedule TEXT NOT NULL, room TEXT NOT NULL, "
                "status TEXT NOT NULL DEFAULT 'Borrowed', returned_at TEXT)"
            )
            cursor.execute("PRAGMA table_info(borrow_records)")
            record_columns = [row[1] for row in cursor.fetchall()]
            if "requested_by" not in record_columns:
                cursor.execute("ALTER TABLE borrow_records ADD COLUMN requested_by TEXT NOT NULL DEFAULT ''")
            cursor.execute(
                "CREATE TABLE IF NOT EXISTS borrow_items ("
                "borrow_item_id INTEGER PRIMARY KEY AUTOINCREMENT, "
                "borrow_id INTEGER NOT NULL, item_id INTEGER NOT NULL, "
                "quantity INTEGER NOT NULL, "
                "FOREIGN KEY(borrow_id) REFERENCES borrow_records(borrow_id), "
                "FOREIGN KEY(item_id) REFERENCES hardware(item_id))"
            )

    def add_item(self, item_name, category, quantity, unit_price):
        try:
            validated = InventoryItemSchema(
                item_name=item_name,
                category=category,
                quantity=quantity,
                unit_price=unit_price,
            )
        except ValidationError as e:
            msg = e.errors()[0]["msg"]
            logger.error(f"Add item validation failed: {msg}")
            return False, msg

        self._ensure_table()

        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT item_name FROM hardware WHERE item_name = ?", (validated.item_name,))
            if cursor.fetchone():
                return False, f"Item '{validated.item_name}' already exists in the database!"

            status = (
                "In Stock"
                if validated.quantity > 5
                else "Low Stock"
                if 1 <= validated.quantity <= 5
                else "Out of Stock"
            )
            try:
                cursor.execute(
                    "INSERT INTO hardware (item_name, category, quantity, unit_price, status) VALUES (?, ?, ?, ?, ?)",
                    (validated.item_name, validated.category, validated.quantity, validated.unit_price, status),
                )
                conn.commit()
                logger.info(f"New inventory item added: '{validated.item_name}'")
                return True, "Item added successfully!"
            except (sqlite3.IntegrityError, psycopg.IntegrityError):
                return False, f"Item '{validated.item_name}' already exists in the database!"
            except (sqlite3.Error, psycopg.Error) as e:
                logger.error(f"Error adding item: {e}")
                return False, "Database insertion failed."

    def fetch_all_items(self):
        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT item_id, item_name, category, quantity, unit_price, status FROM hardware")
                return cursor.fetchall()
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Failed to fetch records: {e}")
            return []

    def get_item_quantity_details(self, item_id):
        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT item_name, quantity FROM hardware WHERE item_id = ?", (item_id,))
                item = cursor.fetchone()
                if not item:
                    return None
                cursor.execute(
                    "SELECT COALESCE(SUM(bi.quantity), 0) "
                    "FROM borrow_items bi JOIN borrow_records br ON br.borrow_id = bi.borrow_id "
                    "WHERE bi.item_id = ? AND br.status = 'Approved'",
                    (item_id,)
                )
                borrowed_quantity = int(cursor.fetchone()[0])
                available_quantity = int(item[1])
                return item[0], available_quantity, borrowed_quantity, available_quantity + borrowed_quantity
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Failed to fetch item quantity details: {e}")
            return None

    def search_items(self, query=None, category=None, status=None):
        """Search hardware items by name (LIKE), and optional category and status filters."""
        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                clauses = []
                params = []
                if query:
                    clauses.append("item_name LIKE ?")
                    params.append(f"%{query}%")
                if category and category.lower() != 'all':
                    clauses.append("category = ?")
                    params.append(category)
                if status and status.lower() != 'all':
                    clauses.append("status = ?")
                    params.append(status)

                sql = "SELECT item_id, item_name, category, quantity, unit_price, status FROM hardware"
                if clauses:
                    sql += " WHERE " + " AND ".join(clauses)
                cursor.execute(sql, tuple(params))
                return cursor.fetchall()
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Search failed: {e}")
            return []

    def get_categories(self):
        """Return distinct categories present in the hardware table."""
        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT DISTINCT category FROM hardware ORDER BY category")
                rows = cursor.fetchall()
                return [r[0] for r in rows]
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Failed to fetch categories: {e}")
            return []

    def total_inventory_value(self):
        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT SUM(quantity * unit_price) FROM hardware")
                result = cursor.fetchone()
                return float(result[0]) if result and result[0] is not None else 0.0
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Failed to compute total inventory value: {e}")
            return 0.0

    def export_to_csv_content(self):
        rows = self.fetch_all_items()
        if not rows:
            return False, "No inventory data available to export."

        try:
            output = io.StringIO(newline="")
            writer = csv.writer(output)
            writer.writerow(["ID", "Name", "Category", "Quantity", "Unit Price", "Status"])
            for row in rows:
                writer.writerow(row)
            return True, output.getvalue()
        except (OSError, csv.Error) as e:
            logger.error(f"CSV export failed: {e}")
            return False, "Failed to generate CSV file."

    def export_to_csv(self, csv_path):
        ok, content = self.export_to_csv_content()
        if not ok:
            return False, content
        try:
            with open(csv_path, mode="w", newline="", encoding="utf-8") as f:
                f.write(content)
            return True, csv_path
        except OSError as e:
            logger.error(f"CSV export failed: {e}")
            return False, "Failed to write CSV file."

    def export_inventory_report(self, csv_path):
        return self.export_to_csv(csv_path)

    def update_quantity(self, item_id, quantity):
        if quantity < 0:
            return False, "Quantity cannot be negative."

        status = (
            "In Stock" if quantity > 5 else "Low Stock" if 1 <= quantity <= 5 else "Out of Stock"
        )

        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute(
                    "UPDATE hardware SET quantity = ?, status = ? WHERE item_id = ?",
                    (quantity, status, item_id),
                )
                if cursor.rowcount == 0:
                    return False, "Selected item does not exist."
                conn.commit()
            logger.info(f"Quantity updated for item ID {item_id} to {quantity}")
            return True, f"Quantity updated to '{quantity}'!"
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Error updating quantity: {e}")
            return False, "Failed to update quantity."

    def update_price(self, item_id, unit_price):
        if unit_price < 0:
            return False, "Price cannot be negative."

        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute(
                    "UPDATE hardware SET unit_price = ? WHERE item_id = ?",
                    (unit_price, item_id),
                )
                if cursor.rowcount == 0:
                    return False, "Selected item does not exist."
                conn.commit()
            logger.info(f"Price updated for item ID {item_id} to {unit_price}")
            return True, f"Price updated to '{unit_price}'!"
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Error updating price: {e}")
            return False, "Failed to update price."

    def delete_item(self, item_id):
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("DELETE FROM hardware WHERE item_id = ?", (item_id,))
                if cursor.rowcount == 0:
                    return False, "Selected item does not exist."
                conn.commit()
            logger.info(f"Item ID {item_id} deleted.")
            return True, f"Item ID {item_id} removed!"
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Error deleting item: {e}")
            return False, "Failed to delete item."

    def borrow_items(self, student_name, student_id, borrow_date, class_name, schedule, room, items, requested_by=""):
        fields = (student_name, student_id, borrow_date, class_name, schedule, room, requested_by)
        if any(not str(value).strip() for value in fields):
            return False, "All student and borrowing details are required."
        if not items:
            return False, "Select at least one item to borrow."

        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                checked_items = []
                for item_id, quantity in items:
                    if int(quantity) <= 0:
                        return False, "Item quantities must be greater than zero."
                    cursor.execute("SELECT item_name, quantity FROM hardware WHERE item_id = ?", (item_id,))
                    row = cursor.fetchone()
                    if not row:
                        return False, "One of the selected items no longer exists."
                    if row[1] < int(quantity):
                        return False, f"Not enough stock for '{row[0]}'. Available: {row[1]}."
                    checked_items.append((item_id, int(quantity)))

                cursor.execute(
                    "INSERT INTO borrow_records (student_name, student_id, borrow_date, class_name, schedule, room, status, requested_by) "
                    "VALUES (?, ?, ?, ?, ?, ?, 'PENDING_BORROW', ?)" + (" RETURNING borrow_id" if is_postgres_enabled() else ""), fields
                )
                borrow_id = cursor.fetchone()[0] if is_postgres_enabled() else cursor.lastrowid
                for item_id, quantity in checked_items:
                    cursor.execute("INSERT INTO borrow_items (borrow_id, item_id, quantity) VALUES (?, ?, ?)",
                                   (borrow_id, item_id, quantity))
                conn.commit()
            return True, f"Transaction request #{borrow_id} submitted for admin approval."
        except (sqlite3.Error, ValueError) as e:
            logger.error(f"Borrow failed: {e}")
            return False, "Failed to create transaction request."

    def borrow_item(self, username, item_id, quantity):
        """Create a pending single-item request without reserving stock."""
        try:
            item_id = int(item_id)
            quantity = int(quantity)
        except (TypeError, ValueError):
            return False, "Item and quantity must be whole numbers."
        if quantity < 1:
            return False, "Borrow quantity must be at least 1."

        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT item_name, quantity FROM hardware WHERE item_id = ?", (item_id,))
                item = cursor.fetchone()
                if not item:
                    return False, "Selected item does not exist."
                if quantity > item[1]:
                    return False, f"Not enough stock for '{item[0]}'. Available: {item[1]}."
                cursor.execute(
                    "INSERT INTO borrow_records (student_name, student_id, borrow_date, class_name, schedule, room, status, requested_by) "
                    "VALUES (?, ?, ?, ?, ?, ?, 'PENDING_BORROW', ?)" + (" RETURNING borrow_id" if is_postgres_enabled() else ""),
                    (username, username, date.today().isoformat(), "Inventory request", "Web", "Web", username),
                )
                borrow_id = cursor.fetchone()[0] if is_postgres_enabled() else cursor.lastrowid
                cursor.execute(
                    "INSERT INTO borrow_items (borrow_id, item_id, quantity) VALUES (?, ?, ?)",
                    (borrow_id, item_id, quantity),
                )
                conn.commit()
            return True, f"Borrow request #{borrow_id} submitted for admin approval."
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Borrow request failed: {e}")
            return False, "Failed to create borrow request."

    @staticmethod
    def _update_status(cursor, item_id):
        cursor.execute("SELECT quantity FROM hardware WHERE item_id = ?", (item_id,))
        quantity = cursor.fetchone()[0]
        status = "In Stock" if quantity > 5 else "Low Stock" if quantity >= 1 else "Out of Stock"
        cursor.execute("UPDATE hardware SET status = ? WHERE item_id = ?", (status, item_id))

    def fetch_borrow_records(self, status=None, requested_by=None, is_admin=False):
        self._ensure_table()
        with self._connect() as conn:
            cursor = conn.cursor()
            sql = "SELECT borrow_id, student_name, student_id, borrow_date, class_name, schedule, room, status, returned_at FROM borrow_records"
            clauses = []
            params = []
            if status:
                clauses.append("status = ?")
                params.append(status)
            if clauses:
                sql += " WHERE " + " AND ".join(clauses)
            cursor.execute(sql + " ORDER BY borrow_id DESC", tuple(params))
            return cursor.fetchall()

    def get_borrow_items(self, borrow_id):
        self._ensure_table()
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT h.item_name, bi.quantity FROM borrow_items bi JOIN hardware h ON h.item_id = bi.item_id WHERE bi.borrow_id = ?",
                (borrow_id,)
            )
            return cursor.fetchall()

    def approve_borrow(self, borrow_id, is_admin=False):
        if not is_admin:
            return False, "Only an administrator can approve transactions."
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT status FROM borrow_records WHERE borrow_id = ?", (borrow_id,))
                record = cursor.fetchone()
                if not record:
                    return False, "Transaction does not exist."
                if record[0] not in ("Pending", "PENDING_BORROW"):
                    return False, "Only pending transactions can be approved."
                cursor.execute("SELECT item_id, quantity FROM borrow_items WHERE borrow_id = ?", (borrow_id,))
                items = cursor.fetchall()
                for item_id, quantity in items:
                    cursor.execute("SELECT item_name, quantity FROM hardware WHERE item_id = ?", (item_id,))
                    item = cursor.fetchone()
                    if not item or item[1] < quantity:
                        return False, f"Not enough stock for '{item[0] if item else 'an item'}'."
                for item_id, quantity in items:
                    cursor.execute("UPDATE hardware SET quantity = quantity - ? WHERE item_id = ?", (quantity, item_id))
                    self._update_status(cursor, item_id)
                cursor.execute("UPDATE borrow_records SET status = 'BORROWED' WHERE borrow_id = ?", (borrow_id,))
                conn.commit()
            return True, f"Transaction #{borrow_id} approved. Inventory updated."
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Approval failed: {e}")
            return False, "Failed to approve transaction."

    def decline_borrow(self, borrow_id, is_admin=False):
        if not is_admin:
            return False, "Only an administrator can decline transactions."
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("UPDATE borrow_records SET status = 'REJECTED_BORROW' WHERE borrow_id = ? AND status IN ('Pending', 'PENDING_BORROW')", (borrow_id,))
                if cursor.rowcount == 0:
                    return False, "Only pending transactions can be declined."
                conn.commit()
            return True, f"Transaction #{borrow_id} declined."
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Decline failed: {e}")
            return False, "Failed to decline transaction."

    def return_borrow(self, borrow_id, is_admin=False):
        if not is_admin:
            return False, "Only an administrator can process returns."
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT status FROM borrow_records WHERE borrow_id = ?", (borrow_id,))
                record = cursor.fetchone()
                if not record:
                    return False, "Transaction does not exist."
                if record[0] not in ("Approved", "BORROWED", "RETURN_PENDING"):
                    return False, "Only approved transactions can be returned."
                cursor.execute("SELECT item_id, quantity FROM borrow_items WHERE borrow_id = ?", (borrow_id,))
                for item_id, quantity in cursor.fetchall():
                    cursor.execute("UPDATE hardware SET quantity = quantity + ? WHERE item_id = ?", (quantity, item_id))
                    self._update_status(cursor, item_id)
                cursor.execute(f"UPDATE borrow_records SET status = 'RETURNED', returned_at = {now_sql()} WHERE borrow_id = ?", (borrow_id,))
                conn.commit()
            return True, f"Transaction #{borrow_id} returned. Inventory updated."
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Return failed: {e}")
            return False, "Failed to process return."

    def get_user_active_loans(self, username):
        return self._loan_rows(username=username, statuses=("Approved", "BORROWED"))

    def get_user_pending_borrows(self, username):
        return self._loan_rows(username=username, statuses=("Pending", "PENDING_BORROW"))

    def get_user_loan_history(self, username):
        return self._loan_rows(username=username)

    def get_pending_borrows(self):
        return self._loan_rows(statuses=("Pending", "PENDING_BORROW"))

    def get_pending_returns(self):
        return self._loan_rows(statuses=("RETURN_PENDING",))

    def get_all_loans_history(self):
        return self._loan_rows()

    def get_request_summaries(self, username=None, statuses=None):
        """Return one summary per parent transaction, including all hardware rows."""
        self._ensure_table()
        with self._connect() as conn:
            cursor = conn.cursor()
            sql = (
                "SELECT br.borrow_id, br.student_name, br.student_id, br.borrow_date, "
                "br.status, br.returned_at, h.item_name, bi.quantity "
                "FROM borrow_records br "
                "JOIN borrow_items bi ON bi.borrow_id = br.borrow_id "
                "JOIN hardware h ON h.item_id = bi.item_id"
            )
            clauses = []
            params = []
            if username:
                clauses.append("br.requested_by = ?")
                params.append(username)
            if statuses:
                clauses.append("br.status IN ({})".format(",".join("?" for _ in statuses)))
                params.extend(statuses)
            if clauses:
                sql += " WHERE " + " AND ".join(clauses)
            cursor.execute(sql + " ORDER BY br.borrow_id DESC, bi.borrow_item_id", params)

            requests = {}
            for row in cursor.fetchall():
                request_id, student_name, student_id, borrow_date, status, returned_at, item_name, quantity = row
                request = requests.setdefault(request_id, {
                    "request_id": request_id,
                    "student_name": student_name,
                    "student_id": student_id,
                    "borrow_date": borrow_date,
                    "status": status,
                    "returned_at": returned_at,
                    "items": [],
                })
                request["items"].append({"name": item_name, "quantity": quantity})
            for request in requests.values():
                request["item_count"] = len(request["items"])
            return list(requests.values())

    def get_request_summary(self, borrow_id):
        requests = self.get_request_summaries()
        return next((request for request in requests if request["request_id"] == int(borrow_id)), None)

    def _loan_rows(self, username=None, statuses=None):
        self._ensure_table()
        with self._connect() as conn:
            cursor = conn.cursor()
            sql = (
                "SELECT br.borrow_id, h.item_name, bi.quantity, br.student_name, "
                "br.borrow_date, br.status, br.returned_at "
                "FROM borrow_records br JOIN borrow_items bi ON bi.borrow_id = br.borrow_id "
                "JOIN hardware h ON h.item_id = bi.item_id"
            )
            clauses = []
            params = []
            if username:
                clauses.append("br.requested_by = ?")
                params.append(username)
            if statuses:
                clauses.append("br.status IN ({})".format(",".join("?" for _ in statuses)))
                params.extend(statuses)
            if clauses:
                sql += " WHERE " + " AND ".join(clauses)
            cursor.execute(sql + " ORDER BY br.borrow_id DESC", params)
            return cursor.fetchall()

    def request_bulk_item_returns(self, loan_ids, username=None):
        if not loan_ids:
            return False, "Select at least one borrowed item to return."
        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                placeholders = ",".join("?" for _ in loan_ids)
                params = list(loan_ids)
                sql = f"UPDATE borrow_records SET status = 'RETURN_PENDING' WHERE borrow_id IN ({placeholders}) AND status IN ('Approved', 'BORROWED')"
                if username:
                    sql += " AND requested_by = ?"
                    params.append(username)
                cursor.execute(sql, params)
                if cursor.rowcount == 0:
                    return False, "No eligible borrowed items were selected."
                conn.commit()
            return True, "Return request submitted for admin approval."
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Return request failed: {e}")
            return False, "Failed to create return request."

    def process_bulk_borrows(self, loan_ids, approve=False):
        if not loan_ids:
            return False, "Select at least one borrow request."
        results = [self.approve_borrow(loan_id, True) if approve else self.decline_borrow(loan_id, True) for loan_id in loan_ids]
        failures = [message for ok, message in results if not ok]
        return (False, failures[0]) if failures else (True, "Borrow requests processed successfully.")

    def process_bulk_returns(self, loan_ids, approve=False):
        if not loan_ids:
            return False, "Select at least one return request."
        if approve:
            results = [self._approve_return(loan_id) for loan_id in loan_ids]
            failures = [message for ok, message in results if not ok]
            return (False, failures[0]) if failures else (True, "Return requests approved and inventory restocked.")
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                placeholders = ",".join("?" for _ in loan_ids)
                cursor.execute(
                    f"UPDATE borrow_records SET status = 'BORROWED' WHERE borrow_id IN ({placeholders}) AND status = 'RETURN_PENDING'",
                    list(loan_ids),
                )
                conn.commit()
            return True, "Return requests rejected; items remain borrowed."
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Return rejection failed: {e}")
            return False, "Failed to reject return requests."

    def _approve_return(self, borrow_id):
        self._ensure_table()
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT status FROM borrow_records WHERE borrow_id = ?", (borrow_id,))
                record = cursor.fetchone()
                if not record or record[0] != "RETURN_PENDING":
                    return False, "Only pending returns can be approved."
                cursor.execute("SELECT item_id, quantity FROM borrow_items WHERE borrow_id = ?", (borrow_id,))
                for item_id, quantity in cursor.fetchall():
                    cursor.execute("UPDATE hardware SET quantity = quantity + ? WHERE item_id = ?", (quantity, item_id))
                    self._update_status(cursor, item_id)
                cursor.execute("UPDATE borrow_records SET status = 'RETURNED', returned_at = datetime('now') WHERE borrow_id = ?", (borrow_id,))
                conn.commit()
            return True, f"Transaction #{borrow_id} returned and restocked."
        except (sqlite3.Error, psycopg.Error) as e:
            logger.error(f"Return approval failed: {e}")
            return False, "Failed to approve return."
