import os
import sqlite3

import psycopg
from logger import logger

DATABASE_URL = os.getenv("DATABASE_URL")


class _PostgresCursor:
    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None, *args, **kwargs):
        query = str(query).replace("?", "%s").replace("datetime('now')", "CURRENT_TIMESTAMP")
        if params is None:
            return self._cursor.execute(query, *args, **kwargs)
        return self._cursor.execute(query, params, *args, **kwargs)

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class _PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self, *args, **kwargs):
        return _PostgresCursor(self._connection.cursor(*args, **kwargs))

    def __enter__(self):
        self._connection.__enter__()
        return self

    def __exit__(self, *args):
        return self._connection.__exit__(*args)

    def __getattr__(self, name):
        return getattr(self._connection, name)


def is_postgres_enabled():
    return bool(DATABASE_URL)


def get_db_connection(db_name="hardware_inventory.db"):
    if DATABASE_URL:
        return _PostgresConnection(psycopg.connect(DATABASE_URL))
    return sqlite3.connect(db_name)


def now_sql():
    return "CURRENT_TIMESTAMP" if is_postgres_enabled() else "datetime('now')"


def column_exists(conn, table_name, column_name):
    cursor = conn.cursor()
    if is_postgres_enabled():
        cursor.execute(
            "SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s)",
            (table_name, column_name),
        )
        return cursor.fetchone()[0]

    cursor.execute(f"PRAGMA table_info({table_name})")
    columns = [row[1] for row in cursor.fetchall()]
    return column_name in columns


def init_db(db_name="hardware_inventory.db"):
    try:
        conn = get_db_connection(db_name)
        cursor = conn.cursor()

        if is_postgres_enabled():
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT UNIQUE NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    locked INTEGER NOT NULL DEFAULT 0,
                    role TEXT NOT NULL DEFAULT 'user'
                )
                """
            )
            if not column_exists(conn, "users", "locked"):
                cursor.execute("ALTER TABLE users ADD COLUMN locked INTEGER NOT NULL DEFAULT 0")
            if not column_exists(conn, "users", "role"):
                cursor.execute("ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user'")

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS password_reset_requests (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    new_password_hash TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'pending',
                    created_at BIGINT NOT NULL,
                    FOREIGN KEY (user_id) REFERENCES users(id)
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS hardware (
                    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_name TEXT NOT NULL,
                    category TEXT NOT NULL,
                    quantity INTEGER NOT NULL,
                    unit_price DOUBLE PRECISION NOT NULL,
                    status TEXT NOT NULL
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS borrow_records (
                    borrow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    student_name TEXT NOT NULL,
                    student_id TEXT NOT NULL,
                    borrow_date TEXT NOT NULL,
                    class_name TEXT NOT NULL,
                    schedule TEXT NOT NULL,
                    room TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'Borrowed',
                    returned_at TEXT
                )
                """
            )
            if not column_exists(conn, "borrow_records", "requested_by"):
                cursor.execute("ALTER TABLE borrow_records ADD COLUMN requested_by TEXT NOT NULL DEFAULT ''")

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS borrow_items (
                    borrow_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    borrow_id BIGINT NOT NULL,
                    item_id BIGINT NOT NULL,
                    quantity INTEGER NOT NULL,
                    FOREIGN KEY (borrow_id) REFERENCES borrow_records(borrow_id),
                    FOREIGN KEY (item_id) REFERENCES hardware(item_id)
                )
                """
            )
        else:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT UNIQUE NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    locked INTEGER DEFAULT 0,
                    role TEXT DEFAULT 'user'
                )
                """
            )

            cursor.execute("PRAGMA table_info(users)")
            cols = [r[1] for r in cursor.fetchall()]
            if 'locked' not in cols:
                try:
                    cursor.execute("ALTER TABLE users ADD COLUMN locked INTEGER DEFAULT 0")
                except sqlite3.OperationalError:
                    pass
            if 'role' not in cols:
                try:
                    cursor.execute("ALTER TABLE users ADD COLUMN role TEXT DEFAULT 'user'")
                except sqlite3.OperationalError:
                    pass

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS password_reset_requests (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    new_password_hash TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'pending',
                    created_at INTEGER NOT NULL,
                    FOREIGN KEY(user_id) REFERENCES users(id)
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS hardware (
                    item_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    item_name TEXT NOT NULL,
                    category TEXT NOT NULL,
                    quantity INTEGER NOT NULL,
                    unit_price REAL NOT NULL,
                    status TEXT NOT NULL
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS borrow_records (
                    borrow_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    student_name TEXT NOT NULL,
                    student_id TEXT NOT NULL,
                    borrow_date TEXT NOT NULL,
                    class_name TEXT NOT NULL,
                    schedule TEXT NOT NULL,
                    room TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'Borrowed',
                    returned_at TEXT
                )
                """
            )
            cursor.execute("PRAGMA table_info(borrow_records)")
            record_columns = [row[1] for row in cursor.fetchall()]
            if "requested_by" not in record_columns:
                cursor.execute("ALTER TABLE borrow_records ADD COLUMN requested_by TEXT NOT NULL DEFAULT ''")
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS borrow_items (
                    borrow_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    borrow_id INTEGER NOT NULL,
                    item_id INTEGER NOT NULL,
                    quantity INTEGER NOT NULL,
                    FOREIGN KEY(borrow_id) REFERENCES borrow_records(borrow_id),
                    FOREIGN KEY(item_id) REFERENCES hardware(item_id)
                )
                """
            )

        conn.commit()
        conn.close()
        logger.info("Database initialized successfully.")
    except (sqlite3.Error, psycopg.Error) as e:
        logger.error(f"Database setup error: {e}")
        raise